/*
 * Copyright 2024 - 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package st.orm.spi.oracle;

import static java.util.stream.Collectors.joining;
import static st.orm.GenerationStrategy.IDENTITY;
import static st.orm.GenerationStrategy.SEQUENCE;

import jakarta.annotation.Nonnull;
import java.util.HashSet;
import java.util.List;
import st.orm.Entity;
import st.orm.PersistenceException;
import st.orm.core.repository.EntityRepository;
import st.orm.core.repository.impl.MergeEntityRepositoryImpl;
import st.orm.core.template.Model;
import st.orm.core.template.ORMTemplate;
import st.orm.core.template.TemplateString;

/**
 * Implementation of {@link EntityRepository} for Oracle.
 */
public class OracleEntityRepositoryImpl<E extends Entity<ID>, ID> extends MergeEntityRepositoryImpl<E, ID> {

    public OracleEntityRepositoryImpl(@Nonnull ORMTemplate ormTemplate, @Nonnull Model<E, ID> model) {
        super(ormTemplate, model);
    }

    @Override
    protected String mergeSourceSuffix() {
        return " FROM DUAL";
    }

    @Override
    protected String versionTimestampExpression() {
        return "SYSTIMESTAMP";
    }

    @Override
    protected TemplateString mergeInsert() {
        var dialect = ormTemplate.dialect();
        var insertDuplicates = new HashSet<>();   // Compound PKs may also have their columns included as stand-alone fields. Only include them once.
        var insertArgs = model.declaredColumns().stream()
                .filter(c -> !c.primaryKey() || c.generation() != IDENTITY)
                .filter(column -> insertDuplicates.add(column.name()))
                .map(c -> c.qualifiedName(dialect))
                .toList();
        var valuesDuplicates = new HashSet<>();   // Compound PKs may also have their columns included as stand-alone fields. Only include them once.
        var valuesArgs = model.declaredColumns().stream()
                .filter(c -> !c.primaryKey() || c.generation() != IDENTITY)
                .filter(column -> valuesDuplicates.add(column.name()))
                .map(c -> "src.%s".formatted(c.qualifiedName(dialect)))
                .toList();
        assert insertArgs.size() == valuesArgs.size();
        if (insertArgs.isEmpty()) {
            return TemplateString.EMPTY;
        }
        String insertSql = insertArgs.stream().collect(joining(", ", "INSERT (", ")"));
        String valuesSql = valuesArgs.stream().collect(joining(", ", "VALUES (", ")"));
        String sql = "\n\t%s\n\t%s".formatted(insertSql, valuesSql);
        return TemplateString.of("\nWHEN NOT MATCHED THEN%s".formatted(sql));
    }

    /**
     * Inserts or updates a collection of entities in the database in batches and returns a list of their IDs.
     *
     * <p>Oracle does not support using sequence-based ID generation together with fetch mode.</p>
     *
     * @param entities an iterable collection of entities to be inserted or updated.
     * @return a list of IDs corresponding to the upserted entities.
     * @throws PersistenceException if the upsert operation fails or if sequence-based ID generation is used.
     */
    @Override
    public List<ID> upsertAndFetchIds(@Nonnull Iterable<E> entities) {
        if (isAutoGeneratedPrimaryKey() && generationStrategy == SEQUENCE) {
            throw new PersistenceException("Oracle does not support using sequence-based ID generation together with fetch mode.");
        }
        return super.upsertAndFetchIds(entities);
    }

    @Override
    public ID insertAndFetchId(@Nonnull E entity) {
        if (generationStrategy != SEQUENCE) {
            return super.insertAndFetchId(entity);
        }
        throw new PersistenceException("Oracle does not support using sequence-based ID generation together with fetch mode.");
    }

    @Override
    public List<ID> insertAndFetchIds(@Nonnull Iterable<E> entities) {
        if (generationStrategy != SEQUENCE) {
            return super.insertAndFetchIds(entities);
        }
        throw new PersistenceException("Oracle does not support using sequence-based ID generation together with fetch mode.");
    }
}
