/*
 * Copyright 2024 - 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package st.orm;

/**
 * Defines the strategy to use when generating values for primary keys.
 *
 * <p>The generation strategy is specified via the {@link PK#generation()} attribute:
 * <pre>{@code
 * record User(@PK(generation = IDENTITY) Integer id,
 *             String name
 * ) implements Entity<Integer> {}
 * }</pre>
 *
 * @see PK#generation()
 * @since 1.6
 */
public enum GenerationStrategy {

    /**
     * No primary key generation is applied. The caller must provide the key value when inserting.
     *
     * <p>Use this strategy when:
     * <ul>
     *   <li>The key is a natural key (e.g., country codes, UUIDs)</li>
     *   <li>The key comes from an external source</li>
     *   <li>The primary key is also a foreign key (dependent one-to-one relationship)</li>
     * </ul>
     *
     * <p>Example with natural key:
     * <pre>{@code
     * record Country(@PK(generation = NONE) String code,
     *                String name
     * ) implements Entity<String> {}
     * }</pre>
     *
     * <p>Example with primary key as foreign key:
     * <pre>{@code
     * record UserProfile(@PK(generation = NONE) @FK User user,
     *                    String bio
     * ) implements Entity<User> {}
     * }</pre>
     */
    NONE,

    /**
     * The primary key is generated by the database using an identity or auto-increment column.
     *
     * <p>This is the default strategy. When inserting, Storm omits the primary key column from the INSERT
     * statement and retrieves the generated value after the insert completes.
     *
     * <p>Example:
     * <pre>{@code
     * record User(@PK Integer id,  // generation = IDENTITY is the default
     *             String name
     * ) implements Entity<Integer> {}
     * }</pre>
     */
    IDENTITY,

    /**
     * The primary key is generated using a database sequence.
     *
     * <p>When inserting, Storm fetches the next value from the sequence before executing the INSERT statement.
     * The sequence name must be specified via {@link PK#sequence()}.
     *
     * <p>Example:
     * <pre>{@code
     * record Order(@PK(generation = SEQUENCE, sequence = "order_seq") Long id,
     *              BigDecimal total
     * ) implements Entity<Long> {}
     * }</pre>
     */
    SEQUENCE
}
