/*
 * Copyright 2024 - 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package st.orm.core.template;

import st.orm.Data;
import st.orm.GenerationStrategy;
import st.orm.Metamodel;

/**
 * Represents a column in a database table.
 */
public interface Column {
    /**
     * Gets the 1-based index of the column.
     *
     * @return the column index.
     */
    int index();

    /**
     * Gets the name of the column.
     *
     * @return the column name.
     */
    String name();

    /**
     * Gets the qualified name of the column including escape characters where necessary.
     *
     * @param dialect the SQL dialect.
     * @return the qualified column name.
     */
    String qualifiedName(SqlDialect dialect);

    /**
     * Gets the type of the column.
     *
     * <p>This is the declared field type: for foreign key columns the referenced entity type, for
     * converter-backed columns the converted field type's parameter type, and the field type otherwise.</p>
     *
     * @return the type of the column.
     */
    Class<?> type();

    /**
     * Gets the Java type of the value as it is persisted to this column.
     *
     * <p>Unlike {@link #type()}, this is the terminal type after following key chains: for a foreign key
     * column it is the type of the referenced key's terminal field (following foreign keys that are
     * themselves primary keys, and record key components), letting callers reason about the physical column
     * without knowledge of key structure. For all other columns it equals {@link #type()}.</p>
     *
     * @return the Java type persisted to this column.
     * @since 1.12
     */
    Class<?> persistedType();

    /**
     * Determines if the column is a primary key.
     *
     * @return true if it is a primary key, false otherwise.
     */
    boolean primaryKey();

    /**
     * Gets the generation strategy for the primary key.
     *
     * @return the generation strategy for the primary key.
     */
    GenerationStrategy generation();

    /**
     * Gets the sequence name for generating the primary key, or empty if the primary key is not generated by a
     * sequence.
     * @return the sequence name for generating the primary key.
     */
    String sequence();

    /**
     * Determines if the column is a foreign key.
     *
     * @return true if it is a foreign key, false otherwise.
     */
    boolean foreignKey();

    /**
     * Gets the generation strategy for the primary key of the referenced (foreign) entity.
     *
     * <p>Only meaningful when {@link #foreignKey()} returns {@code true}. For non-foreign-key columns, this method
     * returns {@link GenerationStrategy#NONE}.</p>
     *
     * @return the generation strategy of the referenced entity's primary key.
     * @since 1.10
     */
    GenerationStrategy foreignKeyGeneration();

    /**
     * The 1-based index of the key.
     *
     * @return the 1-based index of the key.
     */
    int keyIndex();

    /**
     * Determines if the column is nullable.
     *
     * @return true if the column can be null, false otherwise.
     */
    boolean nullable();

    /**
     * Determines if the column is insertable.
     *
     * @return true if the column can be inserted, false otherwise.
     */
    boolean insertable();

    /**
     * Determines if the column is updatable.
     *
     * @return true if the column can be updated, false otherwise.
     */
    boolean updatable();

    /**
     * Determines if the column is used for versioning.
     *
     * @return true if it is a version column, false otherwise.
     */
    boolean version();

    /**
     * Determines if the column is a ref column.
     *
     * @return if the column is a ref column, false otherwise.
     */
    boolean ref();

    /**
     * Returns the metamodel for this element.
     *
     * <p>In case of a foreign key relationship, this metamodel represents the foreign key column on the referencing
     * entity, the entity that declares the foreign key field. The referenced entity's primary key is represented
     * separately by {@link #secondaryMetamodel()}. For non-foreign relationships, this is the only metamodel that
     * applies.</p>
     *
     * @return the metamodel for this element.
     * @since 1.7
     */
    Metamodel<Data, ?> metamodel();

    /**
     * Returns the secondary metamodel associated with this element.
     *
     * <p>This metamodel is only present for foreign key relationships and represents the primary key of the referenced
     * (foreign) entity. For all other cases, this method returns {@code null}.</p>
     *
     * @return the metamodel of the referenced entity's primary key, or {@code null} if this element does not represent
     * a foreign relationship.
     * @since 1.8
     */
    Metamodel<Data, ?> secondaryMetamodel();
}
