= ST/ORM

*Storm* is a SQL Template and ORM framework designed for Java 21 and later versions, focusing on modernizing and simplifying database programming. By leveraging the latest features of Java, it enables developers to define entities and queries in a concise and readable manner, enhancing both productivity and code clarity.

*Key benefits of Storm:*

* *Easy to learn*: With a programming model similar to the Java Persistence API (JPA), developers familiar with JPA can quickly and easily adapt to using Storm.
* *Modern Syntax*: Storm allows for clean and concise code, making it effortless to write entities and queries.
* *Type-safe* The best DSL is no DSL. Storm’s query builder mirrors SQL, providing a type-safe, intuitive experience that makes queries easy to write and read while reducing the risk of runtime errors.
* *Direct Database Interaction*: Storm translates method calls directly into database operations, offering a transparent and straightforward experience. It eliminates inefficiencies like the N+1 query problem for predictable and efficient interactions.
* *Stateless*: Avoids hidden complexities and “magic” with stateless, record-based entities, ensuring simplicity and eliminating lazy initialization and transaction issues downstream.
* *Performance*: Built with efficiency in mind, Storm supports batch processing, lazy streams, and upsert functionality to enhance performance during database interactions.
* *Universal Database Compatibility*: Fully compatible with all SQL databases, it offers flexibility and broad applicability across various database systems.

In summary, Storm delivers a modern, efficient, and straightforward ORM solution that prioritizes ease of use, direct database interaction, and wide compatibility. It’s an excellent choice for Java and Kotlin developers seeking simplicity, performance, and enhanced readability in their database operations.

== Getting Started

Storm offers a flexible and layered approach to database interaction, catering to developers with varying needs and preferences. Whether you’re looking for minimal enhancements or a complete abstraction, Storm has you covered.

=== Dependency Management

Include the following dependencies in your project to start using Storm:

[source,xml,indent=0]
----
<dependencies>
    <dependency>
        <groupId>st.orm</groupId>
        <artifactId>storm</artifactId>
        <version>1.2.0</version>
        <scope>compile</scope>
    </dependency>
    <dependency> <!-- Include for JSON support. -->
        <groupId>st.orm</groupId>
        <artifactId>storm-json</artifactId>
        <version>1.2.0</version>
        <scope>compile</scope>
    </dependency>
    <dependency> <!-- Spring Framework integration. -->
        <groupId>st.orm</groupId>
        <artifactId>storm-spring</artifactId>
        <version>1.2.0</version>
        <scope>compile</scope>
    </dependency>
    <dependency> <!-- Optional database extensions. -->
        <groupId>st.orm</groupId>
        <artifactId>storm-oracle</artifactId>
        <version>1.2.0</version>
        <scope>runtime</scope>
    </dependency>
</dependencies>
----

==== Static Metamodel Generation

Include the following dependency to generate a static metamodel for your entities:

[source,xml,indent=0]
----
<dependency>
    <groupId>st.orm</groupId>
    <artifactId>storm-metamodel-processor</artifactId>
    <version>1.2.0</version>
    <scope>provided</scope>
</dependency>
----
Storm offers a flexible and layered approach to database interaction, catering to developers with varying needs and preferences. Whether you’re looking for minimal enhancements or a complete abstraction, Storm has you covered.

=== Dependency Management

Include the following dependencies in your project to start using Storm:

[source,xml,indent=0]
----
<dependencies>
    <dependency>
        <groupId>st.orm</groupId>
        <artifactId>storm</artifactId>
        <version>1.2.0</version>
        <scope>compile</scope>
    </dependency>
    <dependency> <!-- Include for JSON support. -->
        <groupId>st.orm</groupId>
        <artifactId>storm-json</artifactId>
        <version>1.2.0</version>
        <scope>compile</scope>
    </dependency>
    <dependency> <!-- Spring Framework integration. -->
        <groupId>st.orm</groupId>
        <artifactId>storm-spring</artifactId>
        <version>1.2.0</version>
        <scope>compile</scope>
    </dependency>
    <dependency> <!-- Optional database extensions. -->
        <groupId>st.orm</groupId>
        <artifactId>storm-oracle</artifactId>
        <version>1.2.0</version>
        <scope>runtime</scope>
    </dependency>
</dependencies>
----

=== Level 0 - Parameter Binding
Enhance your existing workflows using technologies like JDBC or JPA, while leveraging Storm for safe and efficient parameter binding. This level is ideal for developers who want to retain control over SQL execution but benefit from Storm’s binding capabilities.

[source,java,indent=0]
----
public class JPAExample {

    @PersistenceContext
    private EntityManager entityManager;

    public List findByBirthDate(LocalDate birthDate) {
        return JpaTemplate.of(entityManager).query(RAW."""
                SELECT *
                FROM pet
                WHERE birth_date = \{birthDate}""")
            .getResultList();
    }
}
----


[source,java,indent=0]
----
public class PreparedStatementExample {

    @Autowired
    private DataSource dataSource;

    public List<Pet> findByBirthDate(LocalDate birthDate) {
        try (PreparedStatement statement = PreparedStatementTemplate.of(dataSource).query(RAW."""
                    SELECT *
                    FROM pet
                    WHERE birth_date = \{birthDate}""");
                ResultSet resultSet = statement.executeQuery()) {
            List<Pet> pets = new ArrayList<>();
            while (resultSet.next()) {
                // ...
            }
            return pets;
        }
    }
}
----


=== Level 1 - Sql Template / Object-Relational Mapping
Take advantage of Storm’s ORM while writing queries using plain, text-based SQL. Storm enhances this approach with automatic joins, table and column resolution, reducing boilerplate and increasing productivity, while producing rich ORM records for seamless interaction with your data.

[source,java,indent=0]
----
public record Pet(
    @PK Integer id,
    String name,
    LocalDate birthDate,
    PetType petType,
    @FK Owner owner
) {}

public record Owner(
    @PK Integer id,
    String firstName,
    String lastName,
    Address address,
    String telephone
) {}

public record Address (
    String address,
    String city
) {}
----

Select all pets that belong to the owner. Uses the auto join feature based on @FK relationships.
[source,java,indent=0]
----
    public List<Pet> findByOwner(Owner owner) {
        return ORM(dataSource).query(RAW."""
                SELECT \{Pet.class}
                FROM \{Pet.class}
                WHERE \{owner}""")
            .getResultList(Pet.class);
    }
----

Count the number of pets that belong to the owner. Uses custom result mapping.
[source,java,indent=0]
----
    public int findPetCountByOwner(Owner owner) {
        return ORM(dataSource)
                .query(RAW."SELECT COUNT(*) FROM \{Pet.class} WHERE \{owner}")
                .getSingleResult(Integer.class);
    }
----


Group by owner and count the number of pets. Uses custom result mapping using a record.
[source,java,indent=0]
----
    public record CountByOwner(Owner owner, int count) {}

    public List<CountByOwner> getPetCount() {
        return ORM(dataSource)
                .query(RAW."SELECT \{Owner.class}, COUNT(*) FROM \{Pet.class} GROUP BY \{Owner.class}.id")
                .getResultList(CountByOwner.class);
    }
----

[source,java,indent=0]
----
    public Pet insert(String name, LocalDate birthDate, PetType petType) {
        var pet = Pet.builder()
                .name(name)
                .birthDate(birthDate)
                .petType(petType)
                .build();
        return ORM(dataSource).query(RAW."""
                INSERT INTO \{Pet.class}
                VALUES \{pet}""")
            .executeUpdate();
    }
----

Insert pets into the database with a batch statement. Uses bind variables.
[source,java,indent=0]
----
    public void insert(List<Pet> pets) {
        var orm = ORM(dataSource);
        var bindVars = orm.createBindVars();
        try (var query = orm.query(RAW."""
                INSERT INTO \{Pet.class}
                VALUES \{bindVars}""".prepare())) {
            pets.forEach(query::addBatch);
            query.executeUpdate();  // Performs the batch update.
        }
    }
----

Updates pets with a batch statement. Uses bind variables.
[source,java,indent=0]
----
    public void update(List<Pet> pets) {
        var orm = ORM(dataSource);
        var bindVars = orm.createBindVars();
        try (var query = orm.query(RAW."""
                UPDATE \{Pet.class}
                SET \{bindVars}
                WHERE \{bindVars}""".prepare())) {
            pets.forEach(query::addBatch);
            query.executeUpdate();  // Performs the batch update.
        }
    }
----

=== Level 2 - Repository
Maximize abstraction by using Storm’s repositories, which provide CRUD logic out of the box. By utilizing a static metamodel, Level 2 can be used in a 100% type-safe manner, ensuring a robust and error-free development experience. This is the recommended level for most use cases. For scenarios requiring a higher level of specialized SQL, Level 2 can be seamlessly combined with Level 1 to leverage text-based SQL when needed, offering the perfect balance between simplicity and advanced query customization.

[source,java,indent=0]
----
    public record Pet(
            @PK Integer id,
            @Nonnull String name,
            @Nonnull LocalDate birthDate,
            @Nonnull PetType petType,
            @Nullable @FK Owner owner
    ) implements Entity<Integer> {}
----

The following example demonstrates how `ORM(datasource).entity(Pet.class)` returns a repository with CRUD features out of the box for the `Pet` entity:

Selects all pets.
[source,java,indent=0]
----
    public List<Pet> findAll() {
        return ORM(dataSource).entity(Pet.class)
            .select()
            .getResultList();   // Use getResultStream() for a lazily loaded stream instead.
    }
----

Select all pets that belong to an owner with the specified first name. Uses the metamodel for column name resolution and utilizes parameter binding.
[source,java,indent=0]
----
    public List<Pet> findByFirstName(String firstName) {
        return ORM(dataSource).entity(Pet.class)
            .select()
            .where(RAW."\{Pet_.owner.firstName} = \{firstName}")
            .getResultList();
    }
----

Use metamodel to identify column.
[source,java,indent=0]
----
    public List<Pet> findByLastName(String lastName) {
        return ORM(dataSource).entity(Pet.class)
            .select()
            .where(Pet_.owner.lastName, EQUALS, lastName)   // Type-safe!
            .getResultList();
    }
----

Build the query using mixed styles.
[source,java,indent=0]
----
    public List<Pet> findByFirstNameAndLastName(String firstName, String lastName) {
        return ORM(dataSource).entity(Pet.class)
            .select()
            .where(it -> it.filter(Pet_.owner.firstName, EQUALS, firstName) // Type-safe!
              .and(it.expression(RAW."\{Pet_.owner.lastName} = \{lastName}"))) // Name resolution / binding.
            .getResultList();
    }
----

Select all pets that belong to the specified owners. Uses the auto join feature based on @FK relationships.
[source,java,indent=0]
----
    public List<Pet> findByOwners(List<Owner> owner) {
        return ORM(dataSource).entity(Pet.class)
            .select()
            .where(Pet_.owner, owners)   // Type-safe!
            .getResultList();
    }
----

Create a new pet with the specified name and pet type. Returns the newly created pet with the generated ID.
[source,java,indent=0]
----
    public Pet insert(String name, LocalDate birthDate, PetType petType) {
        return ORM(dataSource).entity(Pet.class)
            .insert(Pet.builder()
                .name(name)
                .birthDate(birthDate)
                .petType(petType)
                .build());
    }
----

Out of the box insert logic.
[source,java,indent=0]
----
    public void insert(List<Pet> pets) {
        return ORM(dataSource).entity(Pet.class)
            .insert(pets);
    }
----

Out of the box update logic.
[source,java,indent=0]
----
    public void update(List<Pet> pets) {
        return ORM(dataSource).entity(Pet.class)
            .update(pets);
    }
----

The following logic shows howto extend a repository with custom methods:
[source,java,indent=0]
----
public interface PetRepository extends EntityRepository<Pet> {

    default List<Pet> findByOwner(Owner owner) {
        // Use select() to query the Pet table.
        return select()
            .where(Pet_.owner, owner)
            .getResultList();
    }

    default Stream<Pet> findByCity(String city) {
        // Select a lazy loaded stream pets that belong to an owner in the specified city.
        return select()
            .where(Pet_.owner.city, EQUALS, city)
            .getResultStream();
    }

    // Select, Insert, Update, Delete and Upsert methods are inherited from EntityRepository.
}
----

== Additional Features

=== JSON

JSON is supported as a first-class citizen. The following example demonstrates how to use JSON in a repository:

[source,java,indent=0]
----
public record Vet(
    @PK Integer id,
    String firstName,
    String lastName
) implements Entity<Integer> {}

public record Specialty(
    @PK Integer id,
    String name
) implements Entity<Integer> {}

public interface VetRepository extends EntityRepository<Vet> {

    record SpecialtiesByVet(
        Vet vet,
        @Json List<Specialty> specialties
    ) {}

    default List<SpecialtiesByVet> getSpecialties() {
        // Uses VET as the root entity and aggregates the specialties into a JSON object.
        // The result is a list of SpecialtiesByVet records.
        return select(SpecialtiesByVet.class, RAW."\{Vet.class}, JSON_OBJECTAGG(\{Specialty_.id}, \{Specialty_.name})")
            .innerJoin(VetSpecialty.class).on(Vet.class)
            .innerJoin(Specialty.class).on(VetSpecialty.class)
            .groupBy(Vet_.id)
            .getResultList();
    }
}
----

The JSON address field is automatically converted to a map with the keys 'address' and 'city' given that the address field contains the following format: `{ "address": "243 Acalanes Dr", "city": "Sunnyvale" }`

[source,java,indent=0]
----
public record Owner(
    @PK Integer id,
    String firstName,
    String lastName,
    @Json Map<String, String> address,
    String telephone
) implements Entity<Integer> {}

public interface OwnerRepository extends EntityRepository<Owner> {

    // Nothing to do here. The JSON annotation takes care of the conversion.
    // Select, Insert, Update, Delete and Upsert methods are inherited from EntityRepository.

}
----


=== Spring Framework Integration

Spring Framework integration is straightforward. The following example demonstrates how to configure the `ORMTemplate` bean using a `DataSource`.

[source,java,indent=0]
----
@Configuration
public class ORMTemplateConfiguration {

    private final DataSource dataSource;

    public ORMTemplateConfiguration(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    @Bean
    public ORMTemplate ormTemplate() {
        return PreparedStatementTemplate.of(dataSource).toORM();
    }
}
----

The repositories can be made available for dependency injection by extending the `RepositoryBeanFactoryPostProcessor` class.

[source,java,indent=0]
----
@Configuration
public class AcmeRepositoryBeanFactoryPostProcessor extends RepositoryBeanFactoryPostProcessor {

    @Override
    public String[] getRepositoryBasePackages() {
        // Your repository package(s) go here.
        return new String[] { "com.acme.repository" };
    }
}
----

== Future Work

The following examples show how ST/ORM will evolve once String Template 2.0 and Derived Record Creation (JEP 468) can be used.

[source,java,indent=0]
----
public interface PetRepository extends EntityRepository<Pet> {

    record CountByPet(Pet pet, int count) {}

    default List<CountByPet> getVisitCount() {
        // QueryBuilder example with method based String Templates resulting in a much cleaner syntax.
        return select(CountByPet.class, "\{Pet.class}, COUNT(*)")
                .innerJoin(Visit.class).on(Pet.class)
                .groupBy(Vet_.id)
                .getResultList();
    }

    default void removeOwners() {
        // Repository example utilizing derived record creation to update record fields.
        try (var pets = selectAll()) {
            update(pets.map(pet -> pet with { owner = null; });
        }
    }
}
----
