package st.orm.json.model;

import jakarta.annotation.Nonnull;
import lombok.Builder;
import st.orm.FK;
import st.orm.PK;
import st.orm.Persist;
import st.orm.repository.Entity;

@Builder(toBuilder = true)
public record VetSpecialty(
        @Nonnull @PK(autoGenerated = false) VetSpecialtyPK id,  // Implicitly @Inlined
        @Nonnull @FK @Persist(insertable = false) Vet vet,
        @Nonnull @FK @Persist(insertable = false) Specialty specialty) implements Entity<VetSpecialtyPK> {
    public VetSpecialty(@Nonnull VetSpecialtyPK pk) {
        //noinspection DataFlowIssue
        this(pk, null, null);
    }
}
