module storm.spring {
    requires static storm.java;
    requires static storm.micrometer;
    requires static micrometer.observation;
    requires static micrometer.tracing;
    requires static micrometer.commons;
    requires spring.jdbc;
    requires static spring.orm;
    requires static jakarta.persistence;
    requires spring.tx;
    requires spring.context;
    requires spring.beans;
    requires spring.boot;
    requires static org.jspecify;
    requires spring.core;
    requires spring.aop;
    requires static spring.web;
    requires static jakarta.servlet;
    requires static context.propagation;
    requires static spring.boot.actuator;
    requires org.slf4j;
    requires org.aspectj.weaver;
    requires java.logging;
    requires storm.core;
    requires storm.foundation;
    requires spring.boot.autoconfigure;
    requires java.sql;
    exports st.orm.spring;
    exports st.orm.spring.boot;
    exports st.orm.spring.impl;
    provides st.orm.core.spi.ExternalTransactionProvider with st.orm.spring.SpringExternalTransactionProvider;
}
