/*
 * Copyright 2024 - 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package st.orm.core.repository.impl;

import static java.util.function.Predicate.not;
import static java.util.stream.Collectors.joining;
import static st.orm.core.template.SqlInterceptor.intercept;
import static st.orm.core.template.TemplateString.combine;
import static st.orm.core.template.TemplateString.raw;
import static st.orm.core.template.TemplateString.wrap;
import static st.orm.core.template.Templates.bindVar;
import static st.orm.core.template.Templates.table;
import static st.orm.core.template.impl.StringTemplates.flatten;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.math.BigInteger;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicReference;
import java.util.stream.IntStream;
import st.orm.BindVars;
import st.orm.Entity;
import st.orm.PersistenceException;
import st.orm.core.spi.EntityCache;
import st.orm.core.template.Column;
import st.orm.core.template.Model;
import st.orm.core.template.ORMTemplate;
import st.orm.core.template.PreparedQuery;
import st.orm.core.template.SqlTemplateException;
import st.orm.core.template.TemplateString;

/**
 * Shared support for dialects that implement upsert with a SQL {@code MERGE} statement backed by a source query
 * ({@code MERGE INTO t USING (SELECT ... ) src ON (...) WHEN MATCHED ... WHEN NOT MATCHED ...}), such as H2,
 * Oracle and SQL Server.
 *
 * <p>The source query only projects the entity's declared columns — columns of expanded foreign relations are
 * never referenced by the ON, UPDATE or INSERT clauses and are therefore not bound.</p>
 *
 * <p>Dialect differences are expressed as hooks: {@link #castType(Column)} for dialects whose parser cannot infer
 * the type of a bare parameter in the source query (H2), {@link #mergeSourceSuffix()} for dialects that require a
 * FROM clause (Oracle), {@link #statementSuffix()} for dialects that require a statement terminator (SQL Server),
 * the version expressions, and {@link #mergeInsert()} for the dialect-specific WHEN NOT MATCHED clause.</p>
 *
 * @since 1.11
 */
public abstract class MergeEntityRepositoryImpl<E extends Entity<ID>, ID> extends EntityRepositoryImpl<E, ID> {

    protected MergeEntityRepositoryImpl(@Nonnull ORMTemplate ormTemplate, @Nonnull Model<E, ID> model) {
        super(ormTemplate, model);
    }

    /**
     * Returns {@code true} when the entity should be routed to {@link #insert(Entity)} during an upsert.
     *
     * <p>MERGE-based dialects cannot fetch database-generated keys from a MERGE statement, so entities with an
     * auto-generated primary key that is still at its default value are routed to insert. Entities with an
     * auto-generated primary key that carry a non-default value never reach the MERGE either: they are routed to
     * update by {@link #isUpsertUpdate(Entity)}, which takes precedence. As a result, the MERGE path only handles
     * entities whose primary key is not auto-generated.</p>
     *
     * @param entity the entity to check.
     * @return {@code true} if the upsert should be routed to insert.
     */
    @Override
    protected boolean isUpsertInsert(@Nonnull E entity) {
        return isAutoGeneratedPrimaryKey();
    }

    /**
     * Returns the dialect type used to cast a bound parameter of the given column in the MERGE source query, or
     * {@code null} to bind the parameter without a cast. The default implementation returns {@code null}; dialects
     * whose parser cannot infer the type of a bare parameter in the source query's projection override this.
     *
     * @param column the column the parameter belongs to.
     * @return the cast type, or {@code null} for no cast.
     */
    @Nullable
    protected String castType(@Nonnull Column column) {
        return null;
    }

    /**
     * Returns the suffix appended to the MERGE source query, such as {@code " FROM DUAL"} on Oracle. The default
     * implementation returns an empty string.
     */
    protected String mergeSourceSuffix() {
        return "";
    }

    /**
     * Returns the terminator appended to the MERGE statement, such as {@code ";"} on SQL Server. The default
     * implementation returns an empty string.
     */
    protected String statementSuffix() {
        return "";
    }

    /**
     * Returns the expression used to touch a temporal version column on update, such as {@code SYSTIMESTAMP} on
     * Oracle. The default implementation returns {@code CURRENT_TIMESTAMP}.
     */
    protected String versionTimestampExpression() {
        return "CURRENT_TIMESTAMP";
    }

    /**
     * Returns the expression used to increment a numeric version column on update. The default implementation
     * increments the incoming source value.
     *
     * @param qualifiedName the qualified column name.
     */
    protected String versionIncrementExpression(@Nonnull String qualifiedName) {
        return "src.%s + 1".formatted(qualifiedName);
    }

    /**
     * Builds the WHEN NOT MATCHED clause of the MERGE statement. Dialects differ in how auto-generated and
     * sequence-backed columns participate in the insert branch.
     */
    protected abstract TemplateString mergeInsert();

    private String getVersionString(@Nonnull Column column) {
        String columnName = column.qualifiedName(ormTemplate.dialect());
        String updateExpression = switch (column.type()) {
            case Class<?> c when Integer.TYPE.isAssignableFrom(c)
                    || Long.TYPE.isAssignableFrom(c)
                    || Integer.class.isAssignableFrom(c)
                    || Long.class.isAssignableFrom(c)
                    || BigInteger.class.isAssignableFrom(c) -> versionIncrementExpression(columnName);
            case Class<?> c when Instant.class.isAssignableFrom(c)
                    || Date.class.isAssignableFrom(c)
                    || Calendar.class.isAssignableFrom(c)
                    || Timestamp.class.isAssignableFrom(c) -> versionTimestampExpression();
            default ->
                    throw new PersistenceException("Unsupported version type: %s.".formatted(column.type().getSimpleName()));
        };
        return "t.%s = %s".formatted(columnName, updateExpression);
    }

    private TemplateString castColumn(@Nonnull TemplateString parameter, @Nonnull Column column) {
        String alias = column.qualifiedName(ormTemplate.dialect());
        String castType = castType(column);
        if (castType == null) {
            return combine(parameter, TemplateString.of(" AS %s".formatted(alias)));
        }
        return combine(TemplateString.of("CAST("), parameter, TemplateString.of(" AS %s) AS %s".formatted(castType, alias)));
    }

    /**
     * Builds the MERGE source query from the entity's current values. Only declared columns are projected.
     */
    protected TemplateString mergeSelect(@Nonnull E entity) {
        assert !isAutoGeneratedPrimaryKey();
        var duplicates = new HashSet<>();   // Compound PKs may also have their columns included as stand-alone fields. Only include them once.
        try {
            var mapped = model.declaredValues(entity);
            return mapped.entrySet()
                    .stream()
                    .filter(entry -> duplicates.add(entry.getKey().name()))
                    .map(entry -> {
                        Object value = entry.getValue();
                        if (entry.getKey().primaryKey()) {
                            //noinspection unchecked
                            if (model.isDefaultPrimaryKey((ID) value)) {
                                value = null;   // Always pass NULL to force a mismatch.
                            }
                        }
                        return castColumn(wrap(value), entry.getKey());
                    })
                    .reduce((left, right) -> combine(left, TemplateString.of(", "), right))
                    .map(t -> combine(TemplateString.of("SELECT "), t, TemplateString.of(mergeSourceSuffix())))
                    .orElseThrow();
        } catch (SqlTemplateException e) {
            throw new PersistenceException("Failed to map entity to SQL parameters.", e);
        }
    }

    /**
     * Builds the MERGE source query from bind variables. Only declared columns are projected.
     */
    protected TemplateString mergeSelect(@Nonnull BindVars bindVars) {
        var values = new AtomicReference<Map<Column, ?>>();
        bindVars.setRecordListener(record -> {
            try {
                //noinspection unchecked
                values.setPlain(model.declaredValues((E) record));
            } catch (SqlTemplateException e) {
                throw new PersistenceException("Failed to map entity to SQL parameters.", e);
            }
        });
        var duplicates = new HashSet<>();   // Compound PKs may also have their columns included as stand-alone fields. Only include them once.
        return model.declaredColumns().stream()
                .filter(column -> duplicates.add(column.name()))
                .map(c -> castColumn(wrap(bindVar(bindVars, ignore -> values.getPlain().get(c))), c))
                .reduce((left, right) -> combine(left, TemplateString.of(", "), right))
                .map(t -> combine(TemplateString.of("SELECT "), t, TemplateString.of(mergeSourceSuffix())))
                .orElseThrow();
    }

    /**
     * Builds the ON clause by equating primary key columns.
     */
    protected TemplateString mergeOn() {
        var dialect = ormTemplate.dialect();
        var primaryKeys = model.declaredColumns().stream()
                .filter(Column::primaryKey)
                .toList();
        String sql = primaryKeys.stream()
                .map(c -> "t.%s = src.%s".formatted(c.qualifiedName(dialect), c.qualifiedName(dialect)))
                .collect(joining(" AND "));
        return TemplateString.of(sql);
    }

    /**
     * Builds the WHEN MATCHED clause of the MERGE statement.
     */
    protected TemplateString mergeUpdate(@Nonnull AtomicBoolean versionAware) {
        var dialect = ormTemplate.dialect();
        var duplicates = new HashSet<>();   // Compound PKs may also have their columns included as stand-alone fields. Only include them once.
        var args = model.declaredColumns().stream()
                .filter(not(Column::primaryKey))
                .filter(Column::updatable)
                .filter(column -> duplicates.add(column.name()))
                .map(column -> {
                    if (column.version()) {
                        versionAware.setPlain(true);
                        return getVersionString(column);
                    }
                    return "t.%s = src.%s".formatted(column.qualifiedName(dialect), column.qualifiedName(dialect));
                })
                .toList();
        if (args.isEmpty()) {
            return TemplateString.EMPTY;
        }
        String sql = args.stream().collect(joining(", ", "UPDATE SET ", ""));
        return TemplateString.of("\nWHEN MATCHED THEN\n\t%s".formatted(sql));
    }

    @Override
    protected E validateUpsert(@Nonnull E entity) {
        assert !isAutoGeneratedPrimaryKey();
        if (model.isDefaultPrimaryKey(entity.id())) {
            throw new PersistenceException("Primary key must be set for non-auto-generated primary keys for upserts.");
        }
        return entity;
    }

    private TemplateString mergeStatement(@Nonnull TemplateString mergeSelect, @Nonnull AtomicBoolean versionAware) {
        return flatten(raw("""
                MERGE INTO \0 t
                USING (\0) src
                ON (\0)\0\0""" + statementSuffix(),
                table(model.type()), mergeSelect, mergeOn(), mergeUpdate(versionAware), mergeInsert()));
    }

    /**
     * Performs the SQL-level upsert (MERGE) for a single entity, without lifecycle callbacks or routing.
     */
    @Override
    protected void doUpsert(@Nonnull E entity) {
        validateUpsert(entity);
        entityCache().ifPresent(cache -> {
            if (!model.isDefaultPrimaryKey(entity.id())) {
                cache.remove(entity.id());
            }
        });
        var versionAware = new AtomicBoolean();
        intercept(sql -> sql.versionAware(versionAware.getPlain()), () -> {
            var query = ormTemplate.query(mergeStatement(mergeSelect(entity), versionAware)).managed();
            query.executeUpdate();
        });
    }

    /**
     * Performs the SQL-level upsert (MERGE) for a single entity and returns its ID, without lifecycle callbacks
     * or routing.
     */
    @Override
    protected ID doUpsertAndFetchId(@Nonnull E entity) {
        validateUpsert(entity);
        entityCache().ifPresent(cache -> {
            if (!model.isDefaultPrimaryKey(entity.id())) {
                cache.remove(entity.id());
            }
        });
        var versionAware = new AtomicBoolean();
        intercept(sql -> sql.versionAware(versionAware.getPlain()), () -> {
            var query = ormTemplate.query(mergeStatement(mergeSelect(entity), versionAware)).managed();
            query.executeUpdate();
        });
        return entity.id();
    }

    @Override
    protected PreparedQuery prepareUpsertQuery() {
        var bindVars = ormTemplate.createBindVars();
        var versionAware = new AtomicBoolean();
        return intercept(sql -> sql.versionAware(versionAware.getPlain()), () ->
                ormTemplate.query(mergeStatement(mergeSelect(bindVars), versionAware)).managed().prepare());
    }

    @Override
    protected void doUpsertBatch(@Nonnull List<E> batch, @Nonnull PreparedQuery query,
                                 @Nullable EntityCache<E, ID> cache) {
        if (batch.isEmpty()) {
            return;
        }
        batch.stream().map(this::validateUpsert).forEach(query::addBatch);
        if (cache != null) {
            batch.stream()
                    .filter(e -> !model.isDefaultPrimaryKey(e.id()))
                    .forEach(e -> cache.remove(e.id()));
        }
        int[] result = query.executeBatch();
        if (IntStream.of(result).anyMatch(r -> r != 0 && r != 1 && r != 2)) {
            throw new PersistenceException(upsertFailureMessage(batch.size()));
        }
    }

    @Override
    protected List<ID> doUpsertAndFetchIdsBatch(@Nonnull List<E> batch, @Nonnull PreparedQuery query,
                                                @Nullable EntityCache<E, ID> cache) {
        if (batch.isEmpty()) {
            return List.of();
        }
        batch.stream().map(this::validateUpsert).forEach(query::addBatch);
        if (cache != null) {
            batch.stream()
                    .filter(e -> !model.isDefaultPrimaryKey(e.id()))
                    .forEach(e -> cache.remove(e.id()));
        }
        int[] result = query.executeBatch();
        if (IntStream.of(result).anyMatch(r -> r != 0 && r != 1 && r != 2)) {
            throw new PersistenceException(upsertFailureMessage(batch.size()));
        }
        // Entities on the MERGE path always carry their primary key: auto-generated keys are routed to insert or
        // update before reaching this point, and validateUpsert rejects default keys for the rest.
        return batch.stream().map(Entity::id).toList();
    }
}
