blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/storm-orm/storm-framework/discussions
    about: Use GitHub Discussions for questions and general help
