package st.orm.tck;

/**
 * Names a statement the conformance suite pins. The suite asserts the behavior on every dialect; the SQL it generates
 * differs per dialect, so each dialect supplies the text through
 * {@code AbstractEntityRepositoryConformanceTest#expectedSql}. Naming the statements rather than inlining the strings
 * keeps a dialect's expectations in one table, where a missing entry fails
 * {@code AbstractEntityRepositoryConformanceTest#everyPinnedStatementHasAnExpectation} instead of going unnoticed.
 *
 * <p>A constant is added here as its test moves into the shared suite, so this enum tracks what the suite covers
 * rather than what it aims to cover. Tests whose assertions hold on every dialect need no constant at all.
 */
public enum Statement {
    INSERT_AND_FETCH,
    INSERT_AND_FETCH_BATCH,
    INSERT_AND_FETCH_COMPOUND_PK,
    INSERT_AND_FETCH_BATCH_COMPOUND_PK,
    INSERT_AND_FETCH_INLINE,
    INSERT_AND_FETCH_INLINE_BATCH,
    SELECT_LIMIT,
    SELECT_OFFSET,
    SELECT_LIMIT_OFFSET,
    UPDATE_AND_FETCH_INLINE_VERSION,
    UPDATE_AND_FETCH_INLINE_VERSION_BATCH,
    UPSERT,
    UPSERT_BATCH,
    UPSERT_AND_FETCH_BATCH,
    UPSERT_AND_FETCH_INLINE_VERSION,
    UPSERT_INLINE_VERSION_BATCH,
    UPSERT_AND_FETCH_BATCH_EXISTING_COMPOUND_PK,
    UPSERT_AND_FETCH_BATCH_NEW_COMPOUND_PK,
    UPSERT_NON_AUTO_GENERATED,
    UPSERT_AND_FETCH_NON_AUTO_GENERATED,
    UPSERT_AND_FETCH_NON_AUTO_GENERATED_BATCH,
    UPSERT_INLINE_VERSION,
    UPSERT_NON_AUTO_GENERATED_BATCH,
    INSERT_AND_FETCH_WITH_SEQUENCE,
    UPSERT_UNIQUE_KEY,
    UPSERT_WITH_SEQUENCE_EMPTY_NEW,
    INSERT_AND_FETCH_WITH_SEQUENCE_BATCH,
    INSERT_AND_FETCH_WITH_SEQUENCE_EMPTY,
    INSERT_AND_FETCH_WITH_SEQUENCE_EMPTY_BATCH,
    INSERT_AND_FETCH_WITH_SEQUENCE_IGNORE_AUTO_GENERATE,
    INSERT_WITH_SEQUENCE,
    INSERT_WITH_SEQUENCE_EMPTY,
    INSERT_WITH_SEQUENCE_EMPTY_IGNORE_AUTO_GENERATE,
    INSERT_WITH_SEQUENCE_EMPTY_IGNORE_AUTO_GENERATE_BATCH,
    INSERT_WITH_SEQUENCE_EMPTY_IGNORE_AUTO_GENERATE_STREAM,
    INSERT_WITH_SEQUENCE_EMPTY_STREAM,
    INSERT_WITH_SEQUENCE_IGNORE_AUTO_GENERATE_BATCH,
    INSERT_WITH_SEQUENCE_IGNORE_AUTO_GENERATE_STREAM,
    INSERT_WITH_SEQUENCE_STREAM,
    UPSERT_AND_FETCH_WITH_SEQUENCE,
    UPSERT_AND_FETCH_WITH_SEQUENCE_BATCH,
    UPSERT_AND_FETCH_WITH_SEQUENCE_EMPTY,
    UPSERT_AND_FETCH_WITH_SEQUENCE_EMPTY_BATCH,
    UPSERT_WITH_SEQUENCE,
    UPSERT_WITH_SEQUENCE_EMPTY,
    UPSERT_WITH_SEQUENCE_EMPTY_EXISTING,
    UPSERT_WITH_SEQUENCE_EMPTY_EXISTING_BATCH,
    UPSERT_WITH_SEQUENCE_EMPTY_EXISTING_STREAM,
    UPSERT_WITH_SEQUENCE_EMPTY_NEW_BATCH,
    UPSERT_WITH_SEQUENCE_EMPTY_NEW_STREAM,
    UPSERT_WITH_SEQUENCE_EMPTY_STREAM,
    UPSERT_WITH_SEQUENCE_EXISTING,
    UPSERT_WITH_SEQUENCE_EXISTING_BATCH,
    UPSERT_WITH_SEQUENCE_EXISTING_STREAM,
    UPSERT_WITH_SEQUENCE_NEW,
    UPSERT_WITH_SEQUENCE_NEW_BATCH,
    UPSERT_WITH_SEQUENCE_NEW_STREAM,
    UPSERT_WITH_SEQUENCE_STREAM
}
