package st.orm.spi.h2;

import static java.util.Map.entry;

import java.util.List;
import java.util.Map;
import st.orm.tck.AbstractEntityRepositoryConformanceTest;
import st.orm.tck.Expected;
import st.orm.tck.Statement;
import st.orm.test.StormTest;

@StormTest(scripts = "/data.sql")
public class H2EntityRepositoryConformanceTest extends AbstractEntityRepositoryConformanceTest {

    @Override
    protected List<String> schemaDdl() {
        return List.of(
                "DROP TABLE IF EXISTS non_autogen_entity",
                """
                        CREATE TABLE non_autogen_entity (
                        id integer PRIMARY KEY,
                        name varchar(255),
                        version bigint DEFAULT 0
                        )""",
                "INSERT INTO non_autogen_entity (id, name) VALUES (1, 'First')",
                "INSERT INTO non_autogen_entity (id, name) VALUES (2, 'Second')",
                "DROP TABLE IF EXISTS pk_only_entity",
                """
                        CREATE TABLE pk_only_entity (
                        id integer PRIMARY KEY
                        )""",
                "INSERT INTO pk_only_entity (id) VALUES (1)",
                "INSERT INTO pk_only_entity (id) VALUES (2)",
                "DROP TABLE IF EXISTS version_long_entity CASCADE",
                """
                        CREATE TABLE version_long_entity (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(255),
                        version bigint DEFAULT 0
                        )""",
                "INSERT INTO version_long_entity (name) VALUES ('Alice')",
                "INSERT INTO version_long_entity (name) VALUES ('Bob')",
                "DROP TABLE IF EXISTS version_instant_entity CASCADE",
                """
                        CREATE TABLE version_instant_entity (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(255),
                        version timestamp DEFAULT CURRENT_TIMESTAMP
                        )""",
                "INSERT INTO version_instant_entity (name) VALUES ('Alice')",
                "INSERT INTO version_instant_entity (name) VALUES ('Bob')");
    }

    @Override
    protected boolean supportsUpsertFetchWithSequences() {
        return false;
    }

    @Override
    protected Map<Statement, Expected> expectedSql() {
        return Map.ofEntries(
                entry(Statement.INSERT_AND_FETCH, Expected.sql("""
                INSERT INTO vet (first_name, last_name)
                VALUES (?, ?)""").keys("id")),
                entry(Statement.INSERT_AND_FETCH_BATCH, Expected.sql("""
                INSERT INTO vet (first_name, last_name)
                VALUES (?, ?), (?, ?)""").keys("id").bound(false)),
                entry(Statement.INSERT_AND_FETCH_COMPOUND_PK, Expected.sql("""
                INSERT INTO vet_specialty (vet_id, specialty_id)
                VALUES (?, ?)""").keys()),
                entry(Statement.INSERT_AND_FETCH_BATCH_COMPOUND_PK, Expected.sql("""
                INSERT INTO vet_specialty (vet_id, specialty_id)
                VALUES (?, ?)""").keys().bound(true)),
                entry(Statement.INSERT_AND_FETCH_INLINE, Expected.sql("""
                INSERT INTO owner (first_name, last_name, address, city, telephone, version)
                VALUES (?, ?, ?, ?, ?, ?)""").keys("id")),
                entry(Statement.INSERT_AND_FETCH_INLINE_BATCH, Expected.sql("""
                INSERT INTO owner (first_name, last_name, address, city, telephone, version)
                VALUES (?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?)""").keys("id").bound(false)),
                entry(Statement.SELECT_LIMIT, Expected.sql("""
                SELECT o.id, o.first_name, o.last_name, o.address, o.city, o.telephone, o.version
                FROM owner o
                LIMIT 2""")),
                entry(Statement.SELECT_OFFSET, Expected.sql("""
                SELECT o.id, o.first_name, o.last_name, o.address, o.city, o.telephone, o.version
                FROM owner o
                ORDER BY o.id
                OFFSET 1""")),
                entry(Statement.SELECT_LIMIT_OFFSET, Expected.sql("""
                SELECT o.id, o.first_name, o.last_name, o.address, o.city, o.telephone, o.version
                FROM owner o
                ORDER BY o.id
                LIMIT 2 OFFSET 1""")),
                entry(Statement.UPDATE_AND_FETCH_INLINE_VERSION, Expected.sql("""
                UPDATE owner
                SET first_name = ?, last_name = ?, address = ?, city = ?, telephone = ?, version = version + 1
                WHERE id = ? AND version = ?""").keys()),
                entry(Statement.UPDATE_AND_FETCH_INLINE_VERSION_BATCH, Expected.sql("""
                UPDATE owner
                SET first_name = ?, last_name = ?, address = ?, city = ?, telephone = ?, version = version + 1
                WHERE id = ? AND version = ?""").keys().bound(true)),
                entry(Statement.UPSERT_BATCH, Expected.sql("""
                        INSERT INTO vet (first_name, last_name)
                        VALUES (?, ?)""")),
                entry(Statement.UPSERT_AND_FETCH_BATCH, Expected.sql("""
                        UPDATE vet
                        SET first_name = ?, last_name = ?
                        WHERE id = ?""")),
                entry(Statement.UPSERT_AND_FETCH_BATCH_EXISTING_COMPOUND_PK, Expected.sql("""
                        MERGE INTO vet_specialty t
                        USING (SELECT CAST(? AS INTEGER) AS vet_id, CAST(? AS INTEGER) AS specialty_id) src
                        ON (t.vet_id = src.vet_id AND t.specialty_id = src.specialty_id)
                        WHEN NOT MATCHED THEN
                        	INSERT (vet_id, specialty_id)
                        	VALUES (src.vet_id, src.specialty_id)""")),
                entry(Statement.UPSERT_AND_FETCH_INLINE_VERSION, Expected.sql("""
                        UPDATE owner
                        SET first_name = ?, last_name = ?, address = ?, city = ?, telephone = ?, version = version + 1
                        WHERE id = ? AND version = ?""")),
                entry(Statement.UPSERT_INLINE_VERSION_BATCH, Expected.sql("""
                        UPDATE owner
                        SET first_name = ?, last_name = ?, address = ?, city = ?, telephone = ?, version = version + 1
                        WHERE id = ? AND version = ?""")),
                entry(Statement.UPSERT, Expected.sql("""
                        INSERT INTO vet (first_name, last_name)
                        VALUES (?, ?)""")),
                entry(Statement.UPSERT_INLINE_VERSION, Expected.sql("""
                        UPDATE owner
                        SET first_name = ?, last_name = ?, address = ?, city = ?, telephone = ?, version = version + 1
                        WHERE id = ? AND version = ?""")),
                entry(Statement.UPSERT_AND_FETCH_NON_AUTO_GENERATED, Expected.sql("""
                        MERGE INTO specialty t
                        USING (SELECT CAST(? AS INTEGER) AS id, CAST(? AS VARCHAR) AS name) src
                        ON (t.id = src.id)
                        WHEN MATCHED THEN
                        	UPDATE SET t.name = src.name
                        WHEN NOT MATCHED THEN
                        	INSERT (id, name)
                        	VALUES (src.id, src.name)""")),
                entry(Statement.UPSERT_NON_AUTO_GENERATED, Expected.sql("""
                        MERGE INTO specialty t
                        USING (SELECT CAST(? AS INTEGER) AS id, CAST(? AS VARCHAR) AS name) src
                        ON (t.id = src.id)
                        WHEN MATCHED THEN
                        	UPDATE SET t.name = src.name
                        WHEN NOT MATCHED THEN
                        	INSERT (id, name)
                        	VALUES (src.id, src.name)""")),
                entry(Statement.UPSERT_AND_FETCH_BATCH_NEW_COMPOUND_PK, Expected.sql("""
                        MERGE INTO vet_specialty t
                        USING (SELECT CAST(? AS INTEGER) AS vet_id, CAST(? AS INTEGER) AS specialty_id) src
                        ON (t.vet_id = src.vet_id AND t.specialty_id = src.specialty_id)
                        WHEN NOT MATCHED THEN
                        	INSERT (vet_id, specialty_id)
                        	VALUES (src.vet_id, src.specialty_id)""")),
                entry(Statement.UPSERT_AND_FETCH_NON_AUTO_GENERATED_BATCH, Expected.sql("""
                        MERGE INTO specialty t
                        USING (SELECT CAST(? AS INTEGER) AS id, CAST(? AS VARCHAR) AS name) src
                        ON (t.id = src.id)
                        WHEN MATCHED THEN
                        	UPDATE SET t.name = src.name
                        WHEN NOT MATCHED THEN
                        	INSERT (id, name)
                        	VALUES (src.id, src.name)"""))
,
                entry(Statement.UPSERT_NON_AUTO_GENERATED_BATCH, Expected.sql("""
                        MERGE INTO specialty t
                        USING (SELECT CAST(? AS INTEGER) AS id, CAST(? AS VARCHAR) AS name) src
                        ON (t.id = src.id)
                        WHEN MATCHED THEN
                        	UPDATE SET t.name = src.name
                        WHEN NOT MATCHED THEN
                        	INSERT (id, name)
                        	VALUES (src.id, src.name)"""))
);
    }
}
